# Generated by Django 5.2.1 on 2025-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp_main', '0005_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
