# Generated by Django 5.2.1 on 2025-06-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp_main', '0007_alter_task_user_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tasks',
            field=models.ManyToManyField(related_name='user_projects', to='todoApp_main.task'),
        ),
    ]
