# Generated by Django 5.2.1 on 2025-06-10 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp_main', '0008_projects_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='user_projects', to='todoApp_main.task'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
