# Generated by Django 5.2.1 on 2025-06-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp_main', '0010_task_responsible_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='responsible_user',
        ),
    ]
