# Generated by Django 5.2.1 on 2025-06-10 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp_main', '0011_remove_projects_tasks_remove_task_responsible_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsible_user',
            field=models.ManyToManyField(blank=True, related_name='responsible_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
