# Generated by Django 5.2.1 on 2025-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp_main', '0012_task_responsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='user_projects', to='todoApp_main.task'),
        ),
    ]
